# Generated by Django 4.2.7 on 2024-12-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deep_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
