# Generated by Django 4.2.7 on 2024-06-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0002_alter_bottoken_botname_alter_bottoken_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottoken',
            old_name='username',
            new_name='bot_username',
        ),
    ]
