# Generated by Django 4.2.7 on 2024-06-06 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0003_rename_username_bottoken_bot_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDbBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('bot_username', models.CharField(blank=True, max_length=125, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_id', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_field', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'BackupDb',
                'verbose_name_plural': 'BackupDb',
            },
        ),
        migrations.CreateModel(
            name='LogSenderBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('bot_username', models.CharField(blank=True, max_length=125, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_id', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_field', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'LogBot',
                'verbose_name_plural': 'LogBot',
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='bottoken',
            name='bot_token',
        ),
        migrations.RemoveField(
            model_name='bottoken',
            name='bot_username',
        ),
        migrations.RemoveField(
            model_name='bottoken',
            name='botname',
        ),
        migrations.AddField(
            model_name='bottoken',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bottoken',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bottoken',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bottoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
