# Generated by Django 4.2.7 on 2024-06-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0004_backupdbbot_logsenderbot_alter_location_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('movie_channel_username', models.CharField(max_length=64, unique=True)),
                ('movie_bot_username', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
