# Generated by Django 4.2.7 on 2024-06-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0005_supersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='supersettings',
            name='trailer_channel_id',
            field=models.IntegerField(default='-1002080046544', unique=True),
        ),
    ]
