# Generated by Django 4.2.7 on 2024-06-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_bot', '0007_alter_supersettings_trailer_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supersettings',
            name='trailer_channel_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
