full_permission="✅ You have full permission to use the bot \n\n tap to /start"
unsubscribed="❌ Please subscribe to all channels to use the bot"
succes_subscribe="✅ Successfully subscribed"
check_subscribing="check subscribing ✅"
subscribe_channel_text="Please click 👉 'Check Subscription' after subscribing to a channel."